# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Yazdi.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(922, 644)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 30, 877, 481))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.main_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.m1_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.m1_button.setObjectName("m1_button")
        self.verticalLayout.addWidget(self.m1_button)
        self.m2_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.m2_button.setObjectName("m2_button")
        self.verticalLayout.addWidget(self.m2_button)
        self.p1_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.p1_button.setObjectName("p1_button")
        self.verticalLayout.addWidget(self.p1_button)
        self.p2_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.p2_button.setObjectName("p2_button")
        self.verticalLayout.addWidget(self.p2_button)
        self.logr_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.logr_button.setObjectName("logr_button")
        self.verticalLayout.addWidget(self.logr_button)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.window_size_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.window_size_edit.setObjectName("window_size_edit")
        self.horizontalLayout_3.addWidget(self.window_size_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.analyze_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.analyze_button.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.analyze_button.setFont(font)
        self.analyze_button.setDefault(False)
        self.analyze_button.setFlat(False)
        self.analyze_button.setObjectName("analyze_button")
        self.verticalLayout.addWidget(self.analyze_button)
        self.detected_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.detected_label.setObjectName("detected_label")
        self.verticalLayout.addWidget(self.detected_label)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.main_layout.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem)
        self.tab = QtWidgets.QTabWidget(self.horizontalLayoutWidget_2)
        self.tab.setMinimumSize(QtCore.QSize(680, 400))
        self.tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab.setIconSize(QtCore.QSize(16, 16))
        self.tab.setObjectName("tab")
        self.tab_m1 = QtWidgets.QWidget()
        self.tab_m1.setObjectName("tab_m1")
        self.frame_m1 = QtWidgets.QFrame(self.tab_m1)
        self.frame_m1.setGeometry(QtCore.QRect(-1, -1, 671, 461))
        self.frame_m1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_m1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_m1.setObjectName("frame_m1")
        self.tab.addTab(self.tab_m1, "")
        self.tab_m2 = QtWidgets.QWidget()
        self.tab_m2.setObjectName("tab_m2")
        self.frame_m2 = QtWidgets.QFrame(self.tab_m2)
        self.frame_m2.setGeometry(QtCore.QRect(0, 0, 671, 461))
        self.frame_m2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_m2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_m2.setObjectName("frame_m2")
        self.tab.addTab(self.tab_m2, "")
        self.tab_p1 = QtWidgets.QWidget()
        self.tab_p1.setObjectName("tab_p1")
        self.frame_p1 = QtWidgets.QFrame(self.tab_p1)
        self.frame_p1.setGeometry(QtCore.QRect(0, 0, 671, 461))
        self.frame_p1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_p1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_p1.setObjectName("frame_p1")
        self.tab.addTab(self.tab_p1, "")
        self.tab_p2 = QtWidgets.QWidget()
        self.tab_p2.setObjectName("tab_p2")
        self.frame_p2 = QtWidgets.QFrame(self.tab_p2)
        self.frame_p2.setGeometry(QtCore.QRect(0, 0, 671, 461))
        self.frame_p2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_p2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_p2.setObjectName("frame_p2")
        self.tab.addTab(self.tab_p2, "")
        self.tab_logr = QtWidgets.QWidget()
        self.tab_logr.setObjectName("tab_logr")
        self.frame_logr = QtWidgets.QFrame(self.tab_logr)
        self.frame_logr.setGeometry(QtCore.QRect(0, 0, 671, 461))
        self.frame_logr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_logr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_logr.setObjectName("frame_logr")
        self.tab.addTab(self.tab_logr, "")
        self.main_layout.addWidget(self.tab)
        self.output_label = QtWidgets.QLabel(Dialog)
        self.output_label.setGeometry(QtCore.QRect(30, 520, 821, 121))
        self.output_label.setText("")
        self.output_label.setObjectName("output_label")

        self.retranslateUi(Dialog)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Anomaly Detection V 1.1"))
        self.label.setText(_translate("Dialog", "Please import files:"))
        self.m1_button.setText(_translate("Dialog", "M1"))
        self.m2_button.setText(_translate("Dialog", "M2"))
        self.p1_button.setText(_translate("Dialog", "P1"))
        self.p2_button.setText(_translate("Dialog", "P2"))
        self.logr_button.setText(_translate("Dialog", "LogR"))
        self.label_4.setText(_translate("Dialog", "Window size:"))
        self.window_size_edit.setText(_translate("Dialog", "700"))
        self.analyze_button.setText(_translate("Dialog", "Analyze"))
        self.detected_label.setText(_translate("Dialog", "Detected Anomalies:"))
        self.tab.setTabText(self.tab.indexOf(self.tab_m1), _translate("Dialog", "M1 Plot"))
        self.tab.setTabText(self.tab.indexOf(self.tab_m2), _translate("Dialog", "M2 Plot"))
        self.tab.setTabText(self.tab.indexOf(self.tab_p1), _translate("Dialog", "P1 Plot"))
        self.tab.setTabText(self.tab.indexOf(self.tab_p2), _translate("Dialog", "P2 Plot"))
        self.tab.setTabText(self.tab.indexOf(self.tab_logr), _translate("Dialog", "Log R Plot"))
